version: "3"
services:
  backend:
    image: "ghcr.io/gcpug/appengine-go:latest"
    command:
      [
        "dev_appserver.py",
        "--enable_host_checking=False",
        "--default_gcs_bucket_name",
        "default",
        "--log_level=debug",
        "--admin_host=0.0.0.0",
        "--host=0.0.0.0",
        "--port=8899",
        "--storage_path=/data",
        "--runtime_python_path=/usr/bin/python3",
        "--application=dealerbox-test",
        "--datastore_consistency_policy=consistent",
        "--require_indexes=True",
        "app.yaml"
      ]
    ports:
      - "8899:8899"
    working_dir: /app
    volumes:
      - ./server:/app
  admin:
    image: "caddy:2-alpine"
    ports:
      - "8000:8000"
    command: >
      sh -c "echo -e \":8000 {\\n  reverse_proxy {\\n  to backend:8000\\n  header_up Origin http://0.0.0.0:8000\\n}\\n}\" > /Caddyfile && caddy run --config /Caddyfile"
    depends_on:
      - backend
