runtime: go120
app_engine_apis: true

automatic_scaling:
  max_idle_instances: 1
  max_concurrent_requests: 50
  target_cpu_utilization: 0.8
  target_throughput_utilization: 0.9
  max_instances: 10
  min_instances: 0

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
