var categoriesMap = {
  "ART_AND_DESIGN": "Art & Design",
  "AUTO_AND_VEHICLES": "Auto & Vehicles",
  "BEAUTY": "Beauty",
  "BOOKS_AND_REFERENCE": "Books & Reference",
  "BUSINESS": "Business",
  "COMICS": "Comics",
  "COMMUNICATION": "Communication",
  "DATING": "Dating",
  "EDUCATION": "Education",
  "ENTERTAINMENT": "Entertainment",
  "EVENTS": "Events",
  "FINANCE": "Finance",
  "FOOD_AND_DRINK": "Food & Drink",
  "HEALTH_AND_FITNESS": "Health & Fitness",
  "HOUSE_AND_HOME": "House & Home",
  "LIFESTYLE": "Lifestyle",
  "MAPS_AND_NAVIGATION": "Maps & Navigation",
  "MEDICAL": "Medical",
  "MUSIC_AND_AUDIO": "Music & Audio",
  "NEWS_AND_MAGAZINES": "News & Magazines",
  "PARENTING": "Parenting",
  "PERSONALIZATION": "Personalization",
  "PHOTOGRAPHY": "Photography",
  "PRODUCTIVITY": "Productivity",
  "SHOPPING": "Shopping",
  "SOCIAL": "Social",
  "SPORTS": "Sports",
  "TOOLS": "Tools",
  "TRAVEL_AND_LOCAL": "Travel & Local",
  "VIDEO_PLAYERS": "Video Players & Editors",
  "WEATHER": "Weather",
  "LIBRARIES_AND_DEMO": "Libraries & Demo",
  "GAME_ARCADE": "Arcade",
  "GAME_PUZZLE": "Puzzle",
  "GAME_CARD": "Cards",
  "GAME_CASUAL": "Casual",
  "GAME_RACING": "Racing",
  "GAME_SPORTS": "Sport Games",
  "GAME_ACTION": "Action",
  "GAME_ADVENTURE": "Adventure",
  "GAME_BOARD": "Board",
  "GAME_CASINO": "Casino",
  "GAME_EDUCATIONAL": "Educational",
  "GAME_MUSIC": "Music Games",
  "GAME_ROLE_PLAYING": "Role Playing",
  "GAME_SIMULATION": "Simulation",
  "GAME_STRATEGY": "Strategy",
  "GAME_TRIVIA": "Trivia",
  "GAME_WORD": "Word Games",
  "ANDROID_WEAR": "Android Wear",
};

var mixedCategories = {
  // anything with GAME
  "Games": [],
  "Media": [
    "ENTERTAINMENT",
    "MUSIC_AND_AUDIO",
    "PHOTOGRAPHY",
    "VIDEO_PLAYERS",
  ],
  "Misc": [],
  "Recent": [],
  "Frequent": []
};

var packageCategories = {
  "Google": ["com.google", "com.android"]
};

var removedCategories = {
  "APP_WALLPAPER": "App Wallpaper",
  "APP_WIDGETS": "App Widget",
  "GAME_FAMILY": "Family Games",
  "GAME_WALLPAPER": "Wallpaper Games",
  "GAME_WIDGETS": "Widget Games",
  "FAMILY": "Family All Ages",
  "FAMILY_UNDER_5": "Family Ages 5 & Under",
  "FAMILY_6_TO_8": "Family Ages 6-8",
  "FAMILY_9_AND_UP": "Family Ages 9 & Up",
  "FAMILY_ACTION": "Family Action",
  "FAMILY_BRAINGAMES": "Family Brain Games",
  "FAMILY_CREATE": "Family Create",
  "FAMILY_EDUCATION": "Family Education",
  "FAMILY_MUSICVIDEO": "Family Music & Video",
  "FAMILY_PRETEND": "Family Pretend Play",
};
